
version: "3.8"

services:
  rails:

    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - rails.env
    environment:
      DB_USERNAME: vinyl_tracer
      DB_PASSWORD: .env
      DB_DATABASE: vinyl_tracer_production
      DB_PORT: 5432
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "db"

  db:
    image: postgres:13.9-alpine
    env_file:
      - db.env
    environment:
      POSTGRES_USER: vinyl_tracer2
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
